export const COLORS = {
  mainColor: "#0D476B",
  secondColor: "BurlyWood",
  mainText: "#251F47",
  mainBackground: "#D0E2BD",
  buttonText: "#ebf7ff",
  buttonBg: "DarkGoldenRod",
  white: "#ffffff",
  priceCAD: "Crimson",
  priceUSD: "RoyalBlue",
  buttonBgAlert: "Crimson",
  borderColor: "#333333",
  shadowColor: "#999",
  lightBg: "#f4f4f4",
  sectionBg: "#DfE2BD",
};

export const SIZES = {
  buttonWidth: "150px",
  buttonWidthExtended: "200px",
  buttonWidthLrg: "200px",
  buttonHeight: "40px",
  buttonFontSize: "1.2rem",
  buttonBorderRadius: "4px",
  maxWidth: "976px",
  maxWidth1: "780px",
  maxWidth2: "544px",
  maxWidth3: "490px",
  itemCardWidth: "280px",
  itemCardHeight: "425px",
  itemCardImageWidth: "278px",
  itemCardImageHeight: "278px",
  itemCheckoutImageWidth: "120px",
  itemCheckoutImageHeight: "120px",
  minHeight: "100vh",
};